export const demodata = [
    {
        adult: false,
        backdrop_path: '/2RSirqZG949GuRwN38MYCIGG4Od.jpg',
        genre_ids: [53],
        id: 985939,
        original_language: 'en',
        original_title: 'Fall',
        overview:
            'For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights',
        popularity: 6306.828,
        poster_path: '/spCAxD99U1A6jsiePFoqdEcY0dG.jpg',
        release_date: '2022-08-11',
        title: 'Fall',
        video: false,
        vote_average: 7.4,
        vote_count: 837,
    },
    {
        adult: false,
        backdrop_path: '/nnUQqlVZeEGuCRx8SaoCU4XVHJN.jpg',
        genre_ids: [14, 12, 10751],
        id: 532639,
        original_language: 'en',
        original_title: 'Pinocchio',
        overview: 'A wooden puppet embarks on a thrilling adventure to become a real boy.',
        popularity: 4592.717,
        poster_path: '/g8sclIV4gj1TZqUpnL82hKOTK3B.jpg',
        release_date: '2022-09-07',
        title: 'Pinocchio',
        video: false,
        vote_average: 6.8,
        vote_count: 625,
    },
    {
        adult: false,
        backdrop_path: '/1n7ZGr6WeDOW4rFiQKmFel8baWH.jpg',
        genre_ids: [12, 18, 27],
        id: 760741,
        original_language: 'en',
        original_title: 'Beast',
        overview:
            'A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.',
        popularity: 4332.634,
        poster_path: '/iRV0IB5xQeOymuGGUBarTecQVAl.jpg',
        release_date: '2022-08-11',
        title: 'Beast',
        video: false,
        vote_average: 7.1,
        vote_count: 414,
    },
    {
        adult: false,
        backdrop_path: '/hYZ4a0JvPETdfgJJ9ZzyFufq8KQ.jpg',
        genre_ids: [28, 18, 878],
        id: 629176,
        original_language: 'en',
        original_title: 'Samaritan',
        overview:
            'Thirteen year old Sam Cleary  suspects that his mysteriously reclusive neighbor Mr. Smith is actually the legendary vigilante Samaritan, who was reported dead 20 years ago. With crime on the rise and the city on the brink of chaos, Sam makes it his mission to coax his neighbor out of hiding to save the city from ruin.',
        popularity: 3090.172,
        poster_path: '/vwq5iboxYoaSpOmEQrhq9tHicq7.jpg',
        release_date: '2022-08-25',
        title: 'Samaritan',
        video: false,
        vote_average: 7,
        vote_count: 1087,
    },
    {
        adult: false,
        backdrop_path: '/i0Y0wP8H6SRgjr6QmuwbtQbS24D.jpg',
        genre_ids: [28, 18],
        id: 579974,
        original_language: 'te',
        original_title: 'రౌద్రం రణం రుధిరం',
        overview:
            "A fictional history of two legendary revolutionaries' journey away from home before they began fighting for their country in the 1920s.",
        popularity: 2789.346,
        poster_path: '/wE0I6efAW4cDDmZQWtwZMOW44EJ.jpg',
        release_date: '2022-03-24',
        title: 'RRR',
        video: false,
        vote_average: 7.8,
        vote_count: 364,
    },
    {
        adult: false,
        backdrop_path: '/ugS5FVfCI3RV0ZwZtBV3HAV75OX.jpg',
        genre_ids: [16, 878, 28],
        id: 610150,
        original_language: 'ja',
        original_title: 'ドラゴンボール超 スーパーヒーロー',
        overview:
            'The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.',
        popularity: 2413.302,
        poster_path: '/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg',
        release_date: '2022-06-11',
        title: 'Dragon Ball Super: Super Hero',
        video: false,
        vote_average: 8,
        vote_count: 1689,
    },
    {
        adult: false,
        backdrop_path: '/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg',
        genre_ids: [14, 28, 35],
        id: 616037,
        original_language: 'en',
        original_title: 'Thor: Love and Thunder',
        overview:
            'After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.',
        popularity: 2466.001,
        poster_path: '/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg',
        release_date: '2022-07-06',
        title: 'Thor: Love and Thunder',
        video: false,
        vote_average: 6.8,
        vote_count: 3613,
    },
    {
        adult: false,
        backdrop_path: '/geYUecpFI2AonDLhjyK9zoVFcMv.jpg',
        genre_ids: [16, 28, 14],
        id: 810693,
        original_language: 'ja',
        original_title: '劇場版 呪術廻戦 0',
        overview:
            "Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won't leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?",
        popularity: 2503.997,
        poster_path: '/3pTwMUEavTzVOh6yLN0aEwR7uSy.jpg',
        release_date: '2021-12-24',
        title: 'Jujutsu Kaisen 0',
        video: false,
        vote_average: 8,
        vote_count: 349,
    },
    {
        adult: false,
        backdrop_path: '/yaze6df9AMIA9oeDEbIZ4zOTRCJ.jpg',
        genre_ids: [28, 12, 14],
        id: 960700,
        original_language: 'ja',
        original_title: '鋼の錬金術師 完結編 復讐者スカー',
        overview:
            'In this sequel to the 2017 live-action netflix Adaptation of the manga the Elric brothers meet their toughest opponent yet — a lone serial killer with a large scar on his forehead.',
        popularity: 2074.941,
        poster_path: '/c5OwwBNyJkwyroIOIJL9IiRjydR.jpg',
        release_date: '2022-05-20',
        title: 'Fullmetal Alchemist: The Revenge of Scar',
        video: false,
        vote_average: 7,
        vote_count: 104,
    },
    {
        adult: false,
        backdrop_path: '/7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg',
        genre_ids: [53, 28, 878],
        id: 766507,
        original_language: 'en',
        original_title: 'Prey',
        overview:
            'When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.',
        popularity: 1970.527,
        poster_path: '/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg',
        release_date: '2022-08-02',
        title: 'Prey',
        video: false,
        vote_average: 7.9,
        vote_count: 3960,
    },
    {
        adult: false,
        backdrop_path: '/skL7c4ZhZqo1IFbMcHNrol4fvkc.jpg',
        genre_ids: [28, 80, 53],
        id: 921360,
        original_language: 'en',
        original_title: 'Wire Room',
        overview:
            'New recruit Justin Rosa must monitor arms-smuggling cartel member Eddie Flynn — and keep him alive at all costs. When a SWAT team descends on Flynn’s home, Rosa breaks protocol and contacts the gangster directly to save his life. As gunmen break into the Wire Room and chaos erupts, Mueller and Rosa make a final, desperate stand against the corrupt agents and officials who seek to destroy evidence and kill them both.',
        popularity: 1820.525,
        poster_path: '/b9ykj4v8ykjRoGB7SpI1OuxblNU.jpg',
        release_date: '2022-09-02',
        title: 'Wire Room',
        video: false,
        vote_average: 7,
        vote_count: 71,
    },
    {
        adult: false,
        backdrop_path: '/5luJmy21N3bYCkjzRHsoZfvLtPP.jpg',
        genre_ids: [53, 18, 80],
        id: 773975,
        original_language: 'en',
        original_title: 'End of the Road',
        overview:
            'Recently widowed mom Brenda fights to protect her family during a harrowing road trip when a murder and a missing bag of cash plunge them into danger.',
        popularity: 1730.567,
        poster_path: '/tLFIMuPWJHlTJ6TN8HCOiSD6SdA.jpg',
        release_date: '2022-09-09',
        title: 'End of the Road',
        video: false,
        vote_average: 6.6,
        vote_count: 143,
    },
    {
        adult: false,
        backdrop_path: '/qwtT5a7ZiLtUyjGggHmHw958OxT.jpg',
        genre_ids: [53],
        id: 781099,
        original_language: 'fr',
        original_title: 'Inexorable',
        overview:
            'Desperately seeking inspiration for the follow-up novel to his bestseller "Inexorable", Marcel Bellmer moves in his wife\'s old family mansion with his family.',
        popularity: 1757.224,
        poster_path: '/iiclsw6zgRJz5D5Cc6sn4Cs9GQo.jpg',
        release_date: '2022-04-06',
        title: 'Inexorable',
        video: false,
        vote_average: 5.6,
        vote_count: 19,
    },
    {
        adult: false,
        backdrop_path: '/rHzoz94bRfyfNLjiIB26Wt5KDHE.jpg',
        genre_ids: [28, 80, 35, 12],
        id: 773867,
        original_language: 'ko',
        original_title: '서울대작전',
        overview:
            'Chasing speed, dreams and money, a team of drivers get involved in the slush fund investigation of a powerful figure during the 1988 Seoul Olympics.',
        popularity: 1638.898,
        poster_path: '/ffX0TL3uKerLXACkuZGWhAPMbAq.jpg',
        release_date: '2022-08-26',
        title: 'Seoul Vibe',
        video: false,
        vote_average: 6.9,
        vote_count: 74,
    },
    {
        adult: false,
        backdrop_path: '/3PieOs1t6dPHWlgvX3XoqTIQLqN.jpg',
        genre_ids: [12, 28, 878],
        id: 507086,
        original_language: 'en',
        original_title: 'Jurassic World Dominion',
        overview:
            'Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.',
        popularity: 1710.588,
        poster_path: '/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg',
        release_date: '2022-06-01',
        title: 'Jurassic World Dominion',
        video: false,
        vote_average: 7.1,
        vote_count: 3415,
    },
    {
        adult: false,
        backdrop_path: '/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg',
        genre_ids: [28, 18],
        id: 361743,
        original_language: 'en',
        original_title: 'Top Gun: Maverick',
        overview:
            'After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.',
        popularity: 1691.164,
        poster_path: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
        release_date: '2022-05-24',
        title: 'Top Gun: Maverick',
        video: false,
        vote_average: 8.4,
        vote_count: 3873,
    },
    {
        adult: false,
        backdrop_path: '/5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg',
        genre_ids: [27, 53],
        id: 760161,
        original_language: 'en',
        original_title: 'Orphan: First Kill',
        overview:
            'After escaping from an Estonian psychiatric facility, Leena Klammer travels to America by impersonating Esther, the missing daughter of a wealthy family. But when her mask starts to slip, she is put against a mother who will protect her family from the murderous “child” at any cost.',
        popularity: 2288.856,
        poster_path: '/wSqAXL1EHVJ3MOnJzMhUngc8gFs.jpg',
        release_date: '2022-07-27',
        title: 'Orphan: First Kill',
        video: false,
        vote_average: 7.1,
        vote_count: 653,
    },
    {
        adult: false,
        backdrop_path: '/qaTzVAW1u16WFNsepjCrilBuInc.jpg',
        genre_ids: [16, 28, 12],
        id: 539681,
        original_language: 'en',
        original_title: 'DC League of Super-Pets',
        overview:
            'When Superman and the rest of the Justice League are kidnapped, Krypto the Super-Dog must convince a rag-tag shelter pack - Ace the hound, PB the potbellied pig, Merton the turtle and Chip the squirrel - to master their own newfound powers and help him rescue the superheroes.',
        popularity: 1589.069,
        poster_path: '/r7XifzvtezNt31ypvsmb6Oqxw49.jpg',
        release_date: '2022-07-27',
        title: 'DC League of Super-Pets',
        video: false,
        vote_average: 7.5,
        vote_count: 607,
    },
    {
        adult: false,
        backdrop_path: '/9mprVUhXPjdpSaiSon44uG9Dnv2.jpg',
        genre_ids: [35, 28],
        id: 838197,
        original_language: 'it',
        original_title: 'Altrimenti ci arrabbiamo',
        overview:
            "Carezza and Sorriso, brothers very different from each other and in quarrel since childhood, will have to put aside their controversies to recover the legendary Dune Buggy, once belonged to their beloved father and now stolen from him by Torsillo, an unscrupulous building speculator, and his son Raniero. In doing so, they will forge an unusual alliance with a circus community, headed by the beautiful and dangerous Miriam and threatened by Torsillo's dirty business. Between daring chases, memorable fights and delicate meals based on beer and sausages, will the two brothers be able to find their beloved car?",
        popularity: 1484.263,
        poster_path: '/qlrRi05x5hjoM29hz6TDLGTUSop.jpg',
        release_date: '2022-03-23',
        title: "Watch Out, We're Mad",
        video: false,
        vote_average: 5.1,
        vote_count: 70,
    },
    {
        adult: false,
        backdrop_path: '/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg',
        genre_ids: [16, 12, 35, 14],
        id: 438148,
        original_language: 'en',
        original_title: 'Minions: The Rise of Gru',
        overview:
            'A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.',
        popularity: 1426.66,
        poster_path: '/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg',
        release_date: '2022-06-29',
        title: 'Minions: The Rise of Gru',
        video: false,
        vote_average: 7.6,
        vote_count: 2000,
    },
    {
        backdrop_path: '/pdfCr8W0wBCpdjbZXSxnKhZtosP.jpg',
        first_air_date: '2022-09-01',
        genre_ids: [10765, 10759, 18],
        id: 84773,
        name: 'The Lord of the Rings: The Rings of Power',
        origin_country: ['US'],
        original_language: 'en',
        original_name: 'The Lord of the Rings: The Rings of Power',
        overview:
            'Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.',
        popularity: 5486.193,
        poster_path: '/suyNxglk17Cpk8rCM2kZgqKdftk.jpg',
        vote_average: 7.6,
        vote_count: 738,
    },
    {
        backdrop_path: '/Aa9TLpNpBMyRkD8sPJ7ACKLjt0l.jpg',
        first_air_date: '2022-08-21',
        genre_ids: [10765, 18, 10759],
        id: 94997,
        name: 'House of the Dragon',
        origin_country: ['US'],
        original_language: 'en',
        original_name: 'House of the Dragon',
        overview:
            'The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.',
        popularity: 4701.584,
        poster_path: '/z2yahl2uefxDCl0nogcRBstwruJ.jpg',
        vote_average: 8.6,
        vote_count: 1351,
    },
    {
        backdrop_path: '/9GvhICFMiRQA82vS6ydkXxeEkrd.jpg',
        first_air_date: '2022-08-18',
        genre_ids: [35, 10765],
        id: 92783,
        name: 'She-Hulk: Attorney at Law',
        origin_country: ['US'],
        original_language: 'en',
        original_name: 'She-Hulk: Attorney at Law',
        overview:
            'Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.',
        popularity: 4673.523,
        poster_path: '/hJfI6AGrmr4uSHRccfJuSsapvOb.jpg',
        vote_average: 7.2,
        vote_count: 780,
    },
    {
        backdrop_path: '/zymbuoBoL1i94xAOzVJF6IuWLfD.jpg',
        first_air_date: '2018-05-02',
        genre_ids: [10759, 18, 35],
        id: 77169,
        name: 'Cobra Kai',
        origin_country: ['US'],
        original_language: 'en',
        original_name: 'Cobra Kai',
        overview:
            'This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.',
        popularity: 1861.02,
        poster_path: '/6POBWybSBDBKjSs1VAQcnQC1qyt.jpg',
        vote_average: 8.2,
        vote_count: 5041,
    },
    {
        backdrop_path: '/o8zk3QmHYMSC7UiJgFk81OFF1sc.jpg',
        first_air_date: '2022-08-22',
        genre_ids: [10766, 18],
        id: 204095,
        name: 'Mar do Sertão',
        origin_country: ['BR'],
        original_language: 'pt',
        original_name: 'Mar do Sertão',
        overview: '',
        popularity: 1305.678,
        poster_path: '/ixgnqO8xhFMb1zr8RRFsyeZ9CdD.jpg',
        vote_average: 5.8,
        vote_count: 8,
    },
    {
        backdrop_path: '/rIe3PnM6S7IBUmvNwDkBMX0i9EZ.jpg',
        first_air_date: '2011-04-17',
        genre_ids: [10765, 18, 10759],
        id: 1399,
        name: 'Game of Thrones',
        origin_country: ['US'],
        original_language: 'en',
        original_name: 'Game of Thrones',
        overview:
            "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
        popularity: 1261.316,
        poster_path: '/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg',
        vote_average: 8.4,
        vote_count: 19183,
    },
    {
        backdrop_path: '/uGy4DCmM33I7l86W7iCskNkvmLD.jpg',
        first_air_date: '2013-12-02',
        genre_ids: [16, 35, 10765, 10759],
        id: 60625,
        name: 'Rick and Morty',
        origin_country: ['US'],
        original_language: 'en',
        original_name: 'Rick and Morty',
        overview:
            "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
        popularity: 1250.749,
        poster_path: '/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg',
        vote_average: 8.7,
        vote_count: 7026,
    },
    {
        backdrop_path: '/fFeIBjX7Rk6eoEwGMq9jugrV2yP.jpg',
        first_air_date: '2022-09-15',
        genre_ids: [18, 10765],
        id: 125940,
        name: 'Vampire Academy',
        origin_country: ['US'],
        original_language: 'en',
        original_name: 'Vampire Academy',
        overview:
            'In a world of privilege and glamour, two young women’s friendship transcends their strikingly different classes as they prepare to complete their education and enter royal vampire society. Based on the young adult novels by Richelle Mead.',
        popularity: 902.184,
        poster_path: '/fVwWkJBbOtxM7VKg7PS1IkjYpQc.jpg',
        vote_average: 6.9,
        vote_count: 20,
    },
    {
        backdrop_path: '/x0RRnWdYeczF4KXDqW8blda7SKS.jpg',
        first_air_date: '2022-03-28',
        genre_ids: [18, 10766],
        id: 158415,
        name: 'Pantanal',
        origin_country: ['BR'],
        original_language: 'pt',
        original_name: 'Pantanal',
        overview:
            'After the mysterious disappearance of his father, Joventino, the cowboy José Leôncio becomes a wealthy farm owner in Pantanal. Over twenty years have passed and, bitter-hearted because of his father vanishing and the escape of his wife to Rio de Janeiro with his baby, José Leôncio has the chance to make amends with the boy, now a young man raised in the big city with very different values and habits than his own.',
        popularity: 898.141,
        poster_path: '/4Ru1BwcAKWtpM345dWe8YgHf35V.jpg',
        vote_average: 5.6,
        vote_count: 49,
    },
    {
        backdrop_path: '/xZUZ9i6vVayjyhR1vRo9Bjku4h.jpg',
        first_air_date: '2016-01-25',
        genre_ids: [80, 10765],
        id: 63174,
        name: 'Lucifer',
        origin_country: ['US'],
        original_language: 'en',
        original_name: 'Lucifer',
        overview:
            "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
        popularity: 876.249,
        poster_path: '/ekZobS8isE6mA53RAiGDG93hBxL.jpg',
        vote_average: 8.5,
        vote_count: 12476,
    },
    {
        backdrop_path: '/jW61BMd1ZVWPXI7Ts4iC2BTx8Qj.jpg',
        first_air_date: '2022-04-11',
        genre_ids: [18],
        id: 196572,
        name: 'The Secret House',
        origin_country: ['KR'],
        original_language: 'ko',
        original_name: 'The Secret House',
        overview:
            'A story about quitting being a good boy and chasing evil to the end for the sake of the mother and sister who sacrificed for themselves.\n\nA revenge play in which a dirt spoon lawyer chasing the traces of his missing mother walks into the secret surrounding him to fight the world.',
        popularity: 822.012,
        poster_path: '/wNN9hJDV45BF2PiJQQVwBCiqLIl.jpg',
        vote_average: 4.9,
        vote_count: 16,
    },
    {
        backdrop_path: '/7J5d7K4JBDZ4IDODNX3THLggtM5.jpg',
        first_air_date: '2005-03-27',
        genre_ids: [18],
        id: 1416,
        name: "Grey's Anatomy",
        origin_country: ['US'],
        original_language: 'en',
        original_name: "Grey's Anatomy",
        overview:
            'Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.',
        popularity: 820.983,
        poster_path: '/daSFbrt8QCXV2hSwB0hqYjbj681.jpg',
        vote_average: 8.3,
        vote_count: 8419,
    },
    {
        backdrop_path: '/FbUIi5WeDU5j1EtipQ274tts1E.jpg',
        first_air_date: '2022-04-11',
        genre_ids: [35, 18, 10751],
        id: 197352,
        name: 'Bravo, My Life',
        origin_country: ['KR'],
        original_language: 'ko',
        original_name: '으라차차 내 인생',
        overview:
            "Even though Seo Dong Hee comes from a poor family background, she has a bright and positive personality. She dreams of becoming a designer and slowly works her way to achieve her dream. She decides to become the mother of her nephew and raise him by herself. She also gets involved with Kang Cha Yeol. Kang Cha Yeol’s father runs a big company. His father wants him to work for his company, but Kang Cha Yeol doesn't want to. He wants to go back to the U.S., but he realizes he can't do anything without his father's financial support. His father tells Kang Cha Yeol to work for 1 year at his company.",
        popularity: 817.585,
        poster_path: '/3ehMAk8E9zETA9r2ZydwVrgUoP3.jpg',
        vote_average: 7,
        vote_count: 3,
    },
    {
        backdrop_path: '/zJNEXWx3YyWGQioCbutFd5dcNYS.jpg',
        first_air_date: '2022-03-21',
        genre_ids: [10766, 10759, 10751],
        id: 157059,
        name: 'Poliana Moça',
        origin_country: ['BR'],
        original_language: 'pt',
        original_name: 'Poliana Moça',
        overview: '',
        popularity: 799.928,
        poster_path: '/17yQZnnodzS1ZrKcpqHnQV8eQGN.jpg',
        vote_average: 7.9,
        vote_count: 5,
    },
    {
        backdrop_path: '/kOkmTrD8kWLeTXcAEwctg6GwW7t.jpg',
        first_air_date: '2017-02-20',
        genre_ids: [10751, 35],
        id: 91759,
        name: 'Come Home Love: Lo and Behold',
        origin_country: ['HK'],
        original_language: 'cn',
        original_name: 'Come Home Love: Lo and Behold',
        overview:
            "Hung Sue Gan starting from the bottom, established his own logistics company, which is now running smoothly. His only concern now are his three daughters. His eldest daughter has immigrated overseas. His second daughter Hung Yeuk Shui has reached the marriageable age, but has no hopes for marriage anytime soon. She is constantly bickering with her younger sister Hung Sum Yue, who is an honour student, over trivial matters, causing their father to not know whether to laugh or cry. Hung Sue Yan, Hung Sue Gan's brother, moves in with the family, temporarily ending his life as a nomadic photographer. He joins Hung Yeuk Shui's company and encounters Ko Pak Fei, the director of an online shop. The two appear to be former lovers, making for lots of laughter. Since Hung Sue Yan moved in, a series of strange events have occurred in the family. Upon investigation, the source is traced to Lung Ging Fung, a promising young man who is the son of department store mogul Lung Gam Wai.",
        popularity: 795.241,
        poster_path: '/lgD4j9gUGmMckZpWWRJjorWqGVT.jpg',
        vote_average: 3.6,
        vote_count: 10,
    },
    {
        backdrop_path: '/kCx6Ij7hLRnfHbI93UOZxiAAUk3.jpg',
        first_air_date: '2013-09-12',
        genre_ids: [18, 80],
        id: 60574,
        name: 'Peaky Blinders',
        origin_country: ['GB'],
        original_language: 'en',
        original_name: 'Peaky Blinders',
        overview:
            'A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby, who means to move up in the world.',
        popularity: 794.511,
        poster_path: '/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg',
        vote_average: 8.6,
        vote_count: 7436,
    },
    {
        backdrop_path: '/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
        first_air_date: '2016-07-15',
        genre_ids: [18, 10765, 9648],
        id: 66732,
        name: 'Stranger Things',
        origin_country: ['US'],
        original_language: 'en',
        original_name: 'Stranger Things',
        overview:
            'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
        popularity: 783.063,
        poster_path: '/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
        vote_average: 8.6,
        vote_count: 13692,
    },
    {
        backdrop_path: '/eqhKMZTLcieAvoH6CBqknTTfNby.jpg',
        first_air_date: '2022-08-05',
        genre_ids: [10765, 18],
        id: 90802,
        name: 'The Sandman',
        origin_country: ['US'],
        original_language: 'en',
        original_name: 'The Sandman',
        overview:
            'After years of imprisonment, Morpheus — the King of Dreams — embarks on a journey across worlds to find what was stolen from him and restore his power.',
        popularity: 768.292,
        poster_path: '/q54qEgagGOYCq5D1903eBVMNkbo.jpg',
        vote_average: 8.2,
        vote_count: 938,
    },
    {
        backdrop_path: '/ic7YfRS52N3m4oalxoOIT665C33.jpg',
        first_air_date: '2020-07-08',
        genre_ids: [18, 35],
        id: 104877,
        name: 'Love Is In The Air',
        origin_country: ['TR'],
        original_language: 'tr',
        original_name: 'Sen Çal Kapımı',
        overview:
            "Eda, who ties all her hopes to her education, confronts Serkan Bolat, who cuts off her international education scholarship and leaves her with high school diploma. Serkan Bolat offers Eda to give her scholarship back if she pretends to be his fiance for two months. Although Eda rejects the offer of this man as she hates him, she has to accept it when the conditions change. While pretending to be engaged, Serkan and Eda begin to experience a passionate, challenging relationship that will make them forget all they know right. Because love is difficult. And that's why it's amazing.",
        popularity: 765.638,
        poster_path: '/bE71f9A3eztjcd5JT3MmHB8MbzA.jpg',
        vote_average: 8.2,
        vote_count: 2632,
    },
    {
        backdrop_path: '/zaulpwl355dlKkvtAiSBE5LaoWA.jpg',
        first_air_date: '2010-10-31',
        genre_ids: [10759, 18, 10765],
        id: 1402,
        name: 'The Walking Dead',
        origin_country: ['US'],
        original_language: 'en',
        original_name: 'The Walking Dead',
        overview:
            "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
        popularity: 733.143,
        poster_path: '/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg',
        vote_average: 8.1,
        vote_count: 13660,
    },
];
